
CREATE OR ALTER TABLE CORE.FACT_SALES (
  ORDER_ID VARCHAR,
  ORDER_TS TIMESTAMP_NTZ,
  CUSTOMER_SK NUMBER,
  PRODUCT_SK NUMBER,
  QUANTITY NUMBER,
  AMOUNT NUMBER
);

INSERT INTO CORE.FACT_SALES
SELECT
  s.ORDER_ID,
  s.ORDER_TS,
  dc.CUSTOMER_SK,
  dp.PRODUCT_SK,
  s.QUANTITY,
  s.AMOUNT
FROM CORE.STG_SALES s
JOIN CORE.DIM_CUSTOMER dc
  ON dc.CUSTOMER_ID = s.CUSTOMER_ID AND dc.IS_CURRENT = TRUE
JOIN CORE.DIM_PRODUCT dp
  ON dp.PRODUCT_ID  = s.PRODUCT_ID  AND dp.IS_CURRENT = TRUE;
