
CREATE OR REPLACE SCHEMA CORE;

-- Staging tables (simulate raw/landing after ingestion)
CREATE OR ALTER TABLE CORE.STG_CUSTOMER (
  CUSTOMER_ID VARCHAR, NAME VARCHAR, SEGMENT VARCHAR, COUNTRY VARCHAR, UPDATED_TS TIMESTAMP_NTZ
);

CREATE OR ALTER TABLE CORE.STG_PRODUCT (
  PRODUCT_ID VARCHAR, CATEGORY VARCHAR, SUBCATEGORY VARCHAR, UPDATED_TS TIMESTAMP_NTZ
);

CREATE OR ALTER TABLE CORE.STG_SALES (
  ORDER_ID VARCHAR, ORDER_TS TIMESTAMP_NTZ, CUSTOMER_ID VARCHAR, PRODUCT_ID VARCHAR,
  QUANTITY NUMBER, AMOUNT NUMBER
);
