
-- Example orchestration (simplified). In practice, prefer stored procedures if logic grows.
CREATE OR REPLACE TASK CORE.TASK_LOAD_DIM_CUSTOMER
  WAREHOUSE = <WAREHOUSE>
  SCHEDULE = 'USING CRON 15 * * * * UTC'
AS
MERGE INTO CORE.DIM_CUSTOMER tgt
USING (
  SELECT CUSTOMER_ID, NAME, SEGMENT, COUNTRY, UPDATED_TS AS SRC_TS
  FROM CORE.STG_CUSTOMER
) src
ON tgt.CUSTOMER_ID = src.CUSTOMER_ID AND tgt.IS_CURRENT = TRUE
WHEN MATCHED AND (
     NVL(tgt.NAME,'')      <> NVL(src.NAME,'')
  OR NVL(tgt.SEGMENT,'')   <> NVL(src.SEGMENT,'')
  OR NVL(tgt.COUNTRY,'')   <> NVL(src.COUNTRY,'')
) THEN
  UPDATE SET tgt.VALID_TO = src.SRC_TS, tgt.IS_CURRENT = FALSE
WHEN NOT MATCHED BY TARGET THEN
  INSERT (CUSTOMER_ID, NAME, SEGMENT, COUNTRY, VALID_FROM, VALID_TO, IS_CURRENT)
  VALUES (src.CUSTOMER_ID, src.NAME, src.SEGMENT, src.COUNTRY, src.SRC_TS, NULL, TRUE);

CREATE OR REPLACE TASK CORE.TASK_LOAD_DIM_PRODUCT
  WAREHOUSE = <WAREHOUSE>
  AFTER CORE.TASK_LOAD_DIM_CUSTOMER
AS
MERGE INTO CORE.DIM_PRODUCT tgt
USING (
  SELECT PRODUCT_ID, CATEGORY, SUBCATEGORY, UPDATED_TS AS SRC_TS
  FROM CORE.STG_PRODUCT
) src
ON tgt.PRODUCT_ID = src.PRODUCT_ID AND tgt.IS_CURRENT = TRUE
WHEN MATCHED AND (
     NVL(tgt.CATEGORY,'')   <> NVL(src.CATEGORY,'')
  OR NVL(tgt.SUBCATEGORY,'')<> NVL(src.SUBCATEGORY,'')
) THEN
  UPDATE SET tgt.VALID_TO = src.SRC_TS, tgt.IS_CURRENT = FALSE
WHEN NOT MATCHED BY TARGET THEN
  INSERT (PRODUCT_ID, CATEGORY, SUBCATEGORY, VALID_FROM, VALID_TO, IS_CURRENT)
  VALUES (src.PRODUCT_ID, src.CATEGORY, src.SUBCATEGORY, src.SRC_TS, NULL, TRUE);

CREATE OR REPLACE TASK CORE.TASK_LOAD_FACT_SALES
  WAREHOUSE = <WAREHOUSE>
  AFTER CORE.TASK_LOAD_DIM_PRODUCT
AS
INSERT INTO CORE.FACT_SALES
SELECT
  s.ORDER_ID,
  s.ORDER_TS,
  dc.CUSTOMER_SK,
  dp.PRODUCT_SK,
  s.QUANTITY,
  s.AMOUNT
FROM CORE.STG_SALES s
JOIN CORE.DIM_CUSTOMER dc
  ON dc.CUSTOMER_ID = s.CUSTOMER_ID AND dc.IS_CURRENT = TRUE
JOIN CORE.DIM_PRODUCT dp
  ON dp.PRODUCT_ID  = s.PRODUCT_ID  AND dp.IS_CURRENT = TRUE;

-- Enable tasks (CI should control this per environment)
-- ALTER TASK CORE.TASK_LOAD_DIM_CUSTOMER RESUME;
-- ALTER TASK CORE.TASK_LOAD_DIM_PRODUCT  RESUME;
-- ALTER TASK CORE.TASK_LOAD_FACT_SALES   RESUME;
