
CREATE OR ALTER TABLE CORE.DIM_CUSTOMER (
  CUSTOMER_SK NUMBER AUTOINCREMENT,
  CUSTOMER_ID VARCHAR,
  NAME VARCHAR,
  SEGMENT VARCHAR,
  COUNTRY VARCHAR,
  VALID_FROM TIMESTAMP_NTZ,
  VALID_TO   TIMESTAMP_NTZ,
  IS_CURRENT BOOLEAN
);

MERGE INTO CORE.DIM_CUSTOMER tgt
USING (
  SELECT CUSTOMER_ID, NAME, SEGMENT, COUNTRY, UPDATED_TS AS SRC_TS
  FROM CORE.STG_CUSTOMER
) src
ON tgt.CUSTOMER_ID = src.CUSTOMER_ID AND tgt.IS_CURRENT = TRUE
WHEN MATCHED AND (
     NVL(tgt.NAME,'')      <> NVL(src.NAME,'')
  OR NVL(tgt.SEGMENT,'')   <> NVL(src.SEGMENT,'')
  OR NVL(tgt.COUNTRY,'')   <> NVL(src.COUNTRY,'')
) THEN
  UPDATE SET tgt.VALID_TO = src.SRC_TS, tgt.IS_CURRENT = FALSE
WHEN NOT MATCHED BY TARGET THEN
  INSERT (CUSTOMER_ID, NAME, SEGMENT, COUNTRY, VALID_FROM, VALID_TO, IS_CURRENT)
  VALUES (src.CUSTOMER_ID, src.NAME, src.SEGMENT, src.COUNTRY, src.SRC_TS, NULL, TRUE);
