
CREATE OR ALTER TABLE CORE.DIM_PRODUCT (
  PRODUCT_SK NUMBER AUTOINCREMENT,
  PRODUCT_ID VARCHAR,
  CATEGORY VARCHAR,
  SUBCATEGORY VARCHAR,
  VALID_FROM TIMESTAMP_NTZ,
  VALID_TO   TIMESTAMP_NTZ,
  IS_CURRENT BOOLEAN
);

MERGE INTO CORE.DIM_PRODUCT tgt
USING (
  SELECT PRODUCT_ID, CATEGORY, SUBCATEGORY, UPDATED_TS AS SRC_TS
  FROM CORE.STG_PRODUCT
) src
ON tgt.PRODUCT_ID = src.PRODUCT_ID AND tgt.IS_CURRENT = TRUE
WHEN MATCHED AND (
     NVL(tgt.CATEGORY,'')   <> NVL(src.CATEGORY,'')
  OR NVL(tgt.SUBCATEGORY,'')<> NVL(src.SUBCATEGORY,'')
) THEN
  UPDATE SET tgt.VALID_TO = src.SRC_TS, tgt.IS_CURRENT = FALSE
WHEN NOT MATCHED BY TARGET THEN
  INSERT (PRODUCT_ID, CATEGORY, SUBCATEGORY, VALID_FROM, VALID_TO, IS_CURRENT)
  VALUES (src.PRODUCT_ID, src.CATEGORY, src.SUBCATEGORY, src.SRC_TS, NULL, TRUE);
